[theme]
inherit = "pydata_sphinx_theme"
stylesheet = "boa-theme.css"

[options]
repository_url = "https://github.com/bankofamerica/gra-core"
use_edit_page_button = true
show_toc_level = 2
navbar_align = "left"
navbar_center = ["navbar-nav"]
navbar_end = ["navbar-icon-links", "theme-switcher"]
footer_items = ["copyright", "sphinx-version"]
chatbot_enabled = true
